### ISSUE TITLE
Please provide latest version of blockly

### ISSUE THREAD

**Issue by Remorax** [webjars/blockly#11]
The previous version of the Blockly webjar, 36eb0787cc5, was released in Jan 2017 (as mentioned here: https://mvnrepository.com/artifact/org.webjars/blockly/36eb0787cc5), and the Blockly codebase has definitely changed a lot since then.
Can you please update the webjars to the latest version of Blockly?

**Comment by vmassol** [comment]
Note: github repo for blockly's webjar is at https://github.com/webjars/blockly

**Comment by vmassol** [comment]
@jamesward Thanks so much. I work with @Remorax and was pushing him to do the PR but you beat him to it! :) thx again

**Comment by Remorax** [comment]
Thanks a lot @jamesward :)
